### ISSUE TITLE
Settings returns nil for all configurations which reads from environment variables in Rails 4.2.5

### ISSUE THREAD

**Issue by AmitPatel-BoTreeConsulting** [railsconfig/config#134]
`initializers/devise.rb` uses many settings, which seems not able read from environment variables in production.  Few models also use settings from config that read values from environment variables. Such settings also have `nil` values

 **application.rb** 

```
require File.expand_path('../boot', __FILE__)
require 'rails/all'
Bundler.require(*Rails.groups)
module Magnificent
  class Application < Rails::Application
    Config::Integration::Rails::Railtie.preload
  end
end
```

**devise.rb**

```
Devise.setup do |config|
  config.omniauth :twitter, Settings.twitter.consumer_key, Settings.twitter.consumer_secret, strategy_class: OmniAuth::Strategies::Twitter
  config.omniauth :facebook, Settings.facebook.app_id, Settings.facebook.app_secret , { info_fields: 'email,first_name,last_name' , scope: 'email,public_profile' }
end
```

**settings.yml**

```
twitter:
  consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
facebook:
  app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
```

This works perfectly in development environment. Also, When I access `Settings.twitter.consumer_key` from the console in production, it shows the value.

The production environment runs on Phusion Passenger
