### ISSUE TITLE
to_hash uses marshal_dump, incrorrect for integer keys

### ISSUE THREAD

**Issue by batizhevsky** [railsconfig/config#149]
I have integer keys in my Yaml config,  and if I use to_hash they are converted to symbolys
to_hash
`=> {:"79"=> "Value"}`

**Comment by batizhevsky** [comment]
Ok, I've dug that it not simple YAML, and I must to use special types.
From test example:
```
prices:
  type: hash
  contents:
    1: 2.99
```
