### ISSUE TITLE
Raise on non-existent key

### ISSUE THREAD

**Issue by Fryguy** [railsconfig/config#171]
Another useful feature might be an option that instead of returning nil on a non-existent key, would instead raise an exception.  I feel this could be similar to Hash#fetch.

cc @cben

**Comment by aspirewit** [comment]
@Fryguy You can use the validation, [more details](https://github.com/railsconfig/config/pull/155)

**Comment by jcoyne** [comment]
@aspirewit I'm not sure validations would work in every case.  For example I have a configuration like this:

```
app:
  driver:  'foxtrot'
  foxtrot:
   beats: 4
  waltz:
    beats: 3
```

Now I might want to resolve:
```
Settings.app.fetch(Settings.driver)
```
