### ISSUE TITLE
Is that possible using variable in settings.yml

### ISSUE THREAD

**Issue by yuanping** [railsconfig/config#174]
I want to implement this:
```
app:
  protocol: 'http'
  host: 'railsconfig.com'
  port: '80'
  url: "&protocol://&host:&port"
```
I am using this method now, but I feel this method is not good :(
```
<% protocol = 'http' %>
<% host = 'railsconfig.com' %>
<% port = '80' %>
app:
  protocol: <%= protocol %>
  host: <%= host %>
  port: <%= port %>
  url: <%= "#{protocol}://#{host}:#{port}" %>
```
What is the best practice?
