### ISSUE TITLE
Problem with nested objects in yaml

### ISSUE THREAD

**Issue by vedmant** [railsconfig/config#232]
I have following settings.yml:

```
paper_urls:
  - type: pubmed
    prefix: https://www.ncbi.nlm.nih.gov/pubmed/
    regex: \/pubmed\/([\d]+)\/

  - type: doi
    prefix: https://onlinelibrary.wiley.com/doi/
    regex: (10.\d{4,9}\/[-._;()\/:A-Z0-9]+)

  - type: pmc
    prefix: https://www.ncbi.nlm.nih.gov/pmc/articles/
    regex: (PMC[\d]+)

  - type: url
    prefix: https://www.sciencedirect.com/science/article/
    regex:

  - type: url
    prefix: https://academic.oup.com/edrv/article/
    regex:
```

When I parse yaml manually I get expected result:

`puts YAML.load(File.read(Rails.root.join('config', 'settings.yml'))).inspect`

{"paper_urls"=>[{"type"=>"pubmed", "prefix"=>"https://www.ncbi.nlm.nih.gov/pubmed/", "regex"=>"\\/pubmed\\/([\\d]+)\\/"}, {"type"=>"doi", "prefix"=>"https://onlinelibrary.wiley.com/doi/", "regex"=>"(10.\\d{4,9}\\/[-._;()\\/:A-Z0-9]+)"}, {"type"=>"pmc", "prefix"=>"https://www.ncbi.nlm.nih.gov/pmc/articles/", "regex"=>"(PMC[\\d]+)"}, {"type"=>"url", "prefix"=>"https://www.sciencedirect.com/science/article/", "regex"=>nil}, {"type"=>"url", "prefix"=>"https://academic.oup.com/edrv/article/", "regex"=>nil}]}

But when I get settings from Settings object I get something else:

`puts Settings.as_json.inspect`

[["paper_urls", [[["type", "pubmed"], ["prefix", "https://www.ncbi.nlm.nih.gov/pubmed/"], ["regex", "\\/pubmed\\/([\\d]+)\\/"]], [["type", "doi"], ["prefix", "https://onlinelibrary.wiley.com/doi/"], ["regex", "(10.\\d{4,9}\\/[-._;()\\/:A-Z0-9]+)"]], [["type", "pmc"], ["prefix", "https://www.ncbi.nlm.nih.gov/pmc/articles/"], ["regex", "(PMC[\\d]+)"]], [["type", "url"], ["prefix", "https://www.sciencedirect.com/science/article/"], ["regex", nil]], [["type", "url"], ["prefix", "https://academic.oup.com/edrv/article/"], ["regex", nil]]]]]

So instead of array of objects I have array of arrays.
