### ISSUE TITLE
to_hash method doesn't handle YAML arrays of key/value pairs

### ISSUE THREAD

**Issue by reagleton** [railsconfig/config#58]
If the `settings.yml` file contains an array of key/value pairs then the `to_hash` method skips over those pairs and fails to convert them even though it works for simple arrays.

For example, if the `settings.yml` contains,

```
media:
  types:
   - Video
   - Image
   - Website URL
   - Document

  metadata:
   - name: Field 1
     type: string
     required: true
   - name: Field 2
     type: tag
     required: false
   - name: Field 3
     type: text
   - name: Field 4
```

then calling `Settings.media.to_hash` results in,

```
{:types=>["Video", "Image", "Website URL", "Document"], :metadata=>[#<RailsConfig::Options name="Field 1", type="string", required=true>, #<RailsConfig::Options name="Field 2", type="tag", required=false>, #<RailsConfig::Options name="Field 3", type="text">, #<RailsConfig::Options name="Field 4">]}
```

The correct output should probably be,

```
{:types=>["Video", "Image", "Website URL", "Document"], :metadata=>[{:name=>"Field 1", :type=>"string", :required=>true}, {:name=>"Field 2", :type=>"tag", :required=>false}, {:name=>"Field 3", :type=>"text"}, {:name=>"Field 4"}]}
```
